### ISSUE TITLE
Help with Zigbee2Mqtt 

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#1]
Could you help with the Zigbee2Mqtt sensor?
For example here is the payload from the temperature sensor: {"battery":80,"humidity":80.59,"temperature":23.99,"voltage":2965}

Thank you!

**Comment by flic** [comment]
Take a look at zigbee2mqtt_example_sensor in the examples folder, that's pretty much exactly what you're looking for. Copy the raw json, go to Import in Node-RED, paste the whole thing and press the Import button.

https://github.com/flic/node-red-contrib-hal2/blob/main/examples/zigbee2mqtt_example_sensor.json

**Comment by alexsahka** [comment]
I'm blind, Sorry Man. 

Thank you!
