### ISSUE TITLE
Weird NodeRed behavior 

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#10]
Everything in NodeRed works fine until I double click on one of these nodes (imported from your example folder) any nodes in the NodeRed stop opening properties on double click.

![image](https://user-images.githubusercontent.com/7469537/153327157-a9b5db0b-605f-41ab-a56c-c469b1533f60.png)

After refreshing the browser (Chrome) everything works fine again until double click on these nodes, anyone can reproduce this behavior?

NodeRed V: 2.1.4, node-red-contrib-hal2 V: 1.9.8

**Comment by flic** [comment]
Strange. I couldn't reproduce in 2.1.3 or 2.2.0 but I'll look into it a bit more.

**Comment by flic** [comment]
Are you seeing any console errors in Chrome?

![Skärmavbild 2022-02-10 kl  08 06 10](https://user-images.githubusercontent.com/400673/153355368-d9088a75-49b1-4892-9b9d-4cee2ed99bc9.png)

**Comment by alexsahka** [comment]
Here are errors in Chrome
![image](https://user-images.githubusercontent.com/7469537/153355970-1bd36305-5735-4c1d-8e2f-bfc0e34dc0d6.png)

**Comment by flic** [comment]
Seems to be a problem with the example thingTypes that doesn't seem to be registered correctly. Im guessing something went wrong when you imported the example. I pushed a new version 1.9.9 with better error handling, could you try that?

**Comment by alexsahka** [comment]
Upgraded to version 1.9.9, deleted example then imported again, and everything working as it should, Thanks!
