### ISSUE TITLE
Event Handler Purpose.

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#11]
Could you explain the "event handler" purpose?

I would agree if... by selecting event handler limit "Thing" selection automatically, where the "Thing" is present.

 Otherwise, it is kind of not easy to use, always need to check where is that "Thing" resides.

![image](https://user-images.githubusercontent.com/7469537/155425364-3eb3c77a-8134-4a8d-a9b4-d2705c9ade51.png)

**Comment by flic** [comment]
The event handler config only exists to give me a central location to handle events between nodes and to check heartbeats.

If Thing A emits an event (a value change) and Trigger B wants to take action on that event I need a central location to handle event subscriptions and event emits for them to talk to each other, and that's the event handler config.

If I could automatically create a configuration node invisible in the background that's what I would do but that's not possible in Node-RED, it needs to be visible in the GUI and manually created by the user.

My  suggestion is to create one event handler and to use that one for everything, there's really no reason to create multiple event handlers unless you for some reason wants to keep parts of your setup from talking to other parts.

**Comment by alexsahka** [comment]
What confuses me is this: Max event listeners. The question then is why there is a limit?
![image](https://user-images.githubusercontent.com/7469537/155481351-63b25dca-3367-4af5-b998-815b143abec7.png)

**Comment by flic** [comment]
It's a Javscript thing to guard against memory leaks if the code keeps adding listeners and doesn't remove them. Set it to 0 to disable the warning.

**Comment by alexsahka** [comment]
OK thanks
