### ISSUE TITLE
Egress references in Main tab disappear 

### ISSUE THREAD

**Issue by minedaddy** [flic/node-red-contrib-hal2#15]
Hi,

Hal2 has been working perfectly for many months. I've recently made some minor adjustments, in various flows, but those flows containing Hal2 Things began to fail. I discovered that references to the Egress functions on the "Main" tab of the Thing were missing.  Ingress references are OK and the Egress functions themselves remain intact. I recreated the missing references and all was well until I made another change to a Hal2 thing and the setups disappeared again. They all disappear together, whether or not they were involved in a change, and, of course Item selections made in, for example, an Event node for the same Thing, disappear. 

I have another group of Things with a separate Event Handler and that is behaving the same way.

I began to modify my flows after updating Hal2 to 1.14.0 a few days ago but I can't say if the update had anything to do with the problems I'm experiencing. All the Egress functions are Command Only and all the Context Stores for all Things is "default". Other nodes and flows in my system work as expected and only the Hal2 things are affected.

I have not been able to determine what triggers the disappearance.

Please let me know if you have any insights as to what is going on or what I can do to locate the source of the problem.

Thanks for your assistance!

**Comment by minedaddy** [comment]
So it looks like everything is stable and functions perfectly until I double-click an event node. Even without changing any parameters, the act of opening the property edit form clears the Egress references (in the Main tab of the Edit Thing Type node) for the related Thing. Other Things are left unchanged until I try to edit an event node for that Thing.

**Comment by flic** [comment]
Thanks for the detailed info! I did make some changes to the event node in 1.14 so it doesn't sound unreasonable that I screwed something up. I'll take a look at it as soon as possible. It might be a good idea to rollback to 1.13.0 in the meantime.

npm i node-red-contrib-hal2@1.13.0

**Comment by flic** [comment]
Pretty sure I got it. I'm just gonna run some tests and then I'll push 1.14.1 with a fix. Sorry 'bout that!

**Comment by flic** [comment]
1.14.1 is out. Let me know if it fixes your problem!

**Comment by minedaddy** [comment]
That did the trick, Fredrik! Thanks!
