### ISSUE TITLE
Grouping "thing"

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#2]
I can't find how to group "thing".
For example, I have Zigbee, WIFI or even virtual devices is it possible to group and later filter by selecting group members from the menu? Asking this because it becomes a large list of devices after time, and very difficult to find later in between hundreds of real or virtual devices.  Kinda same question:
https://github.com/flic/node-red-contrib-hal/issues/27#issuecomment-950119036

![image](https://user-images.githubusercontent.com/7469537/147136895-0e701f01-9efb-41a9-82ea-e1a1c185bcee.png)

**Comment by flic** [comment]
Oh, I get it! You want to group certain devices, but not really to use them as a group but to use the group as a filter in the selection GUI? Did I get that right? Not possible right now but that's an interesting idea, need to think on that some...

**Comment by alexsahka** [comment]
Yes, filtering/grouping, etc. For example, in node-red-contrib-hal I have around 100+ items and sometimes it is very difficult to find one.

**Comment by flic** [comment]
What do you think of this solution, the ability to filter on type?

![Skärmavbild 2021-12-23 kl  13 07 46](https://user-images.githubusercontent.com/400673/147239044-fd599281-f7f3-49f8-b104-7be62b30812e.png)

![Skärmavbild 2021-12-23 kl  13 07 56](https://user-images.githubusercontent.com/400673/147239060-9df12b3b-b4c1-48d2-8e86-1b506c59f952.png)

![Skärmavbild 2021-12-23 kl  13 08 13](https://user-images.githubusercontent.com/400673/147239069-9bb678e7-afbf-4b37-bd62-b6c6593003c9.png)

**Comment by alexsahka** [comment]
I think it will work. Just need something to reduce the list of Items by grouping. (ZigbeeGateway, Z2M, Shelly, EspEasy, Virtual, etc. )

**Comment by alexsahka** [comment]
Is this updated in the NoderRed repository?

**Comment by flic** [comment]
Now it is, v1.1.0

**Comment by alexsahka** [comment]
Thank you!
