### ISSUE TITLE
Templating Load Library is not visible with latest NodeRed v3.0.2 

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#24]
After updating to the latest NodeRed v3.0.2 templating Save to Library is visible and working, but the Load Library is not visible.

**Comment by flic** [comment]
Verified, I have the same problem in v3.0.0. Still works in v2.x. I'll look into it.

**Comment by flic** [comment]
Fixed in v1.14.5

**Comment by alexsahka** [comment]
Thank you!
