### ISSUE TITLE
Home assistant NodeRed addon memory only in Context store

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#26]
Home assistant NodeRed addon memory only in Context store no file option.

![image](https://user-images.githubusercontent.com/7469537/188496321-4a8ac1b6-87a9-4aaa-93cb-c106e2b965eb.png)

NodeRed : 
![image](https://user-images.githubusercontent.com/7469537/188496400-e760d505-2ed9-4b67-b275-309a23e5078e.png)

Hal2: 
![image](https://user-images.githubusercontent.com/7469537/188496459-8c3307be-990e-4580-8373-3db244a39e02.png)

**Comment by flic** [comment]
Tried this on three different Node-RED installations, standalone and Docker, Node-RED v3.0.0 and v3.0.2, can't recreate. Must be related to something with the Home Assistant Node-RED add-on combo, can't help you with that one.

**Comment by alexsahka** [comment]
After using Node-red on the Home Assistant for 2 days I stopped, too many unusual problems compared to Node-red in the Docker for example. Thank you anyway.

**Comment by alexsahka** [comment]
Solved this by enabling "Saving context data to the file-system"  this is disabled in settings.js by default:
https://nodered.org/docs/user-guide/context

Saving context data to the file-system
To enable file-based storage, the following option can be used:

contextStorage: {
   default: {
       module: "localfilesystem"
   }
}

**Comment by alexsahka** [comment]
Please add this information somewhere in the help.

Thanks.

**Comment by flic** [comment]
Good point. On it.
