### ISSUE TITLE
Need an advise.

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#27]
I've used node-red-contrib-hal before, and in node-red-contrib-hal it's very easy to look up where an item is used in node-red.
![image](https://user-images.githubusercontent.com/7469537/209056192-1b6e7fd6-5239-43ba-8601-800372f23e13.png)

Is there a way to find node-red-contrib-hal2 where this item is used?

**Comment by flic** [comment]
Hmm, I'm afraid I I don't know. I haven't really thought about that before.

**Comment by alexsahka** [comment]
Interesting, I thought you made this option to search in node-red-contrib-hal.

**Comment by flic** [comment]
Maybe this'll help you? I added an infobutton to the Things-node in 1.15.0 that'll show you all the places it's used:

<img width="687" alt="Skärmavbild 2023-01-26 kl  19 23 45" src="https://user-images.githubusercontent.com/400673/214919876-e5dab403-a9d1-44bd-a1d3-d24b52fff314.png">

**Comment by alexsahka** [comment]
This is a great solution and works very well, Thank You!
