### ISSUE TITLE
Zigbee2MQTT Check Alive not working

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#4]
Zigbee2MQTT Check Alive not working, tried from 5 to 60 sec the status is still green, and I know there is no update in this period.
Even disconnecting MQTT IN doesn't help
![image](https://user-images.githubusercontent.com/7469537/147458830-9aa06d2a-f9cd-4d50-bdc7-9b6fc1c3277d.png)

![image](https://user-images.githubusercontent.com/7469537/147459099-55a9cdfb-8d5c-452f-9a17-0f3b3ee68624.png)

**Comment by flic** [comment]
Fixed in v1.2.1

**Comment by alexsahka** [comment]
Thank you.

**Comment by flic** [comment]
You might want to update to 1.3.0, I forgot to save heartbeat to context store in 1.2.1. Some new changes to the Action and Value nodes as well.

**Comment by alexsahka** [comment]
Something not right with 1.3.0 
If I unselect  Check Alive for one sensor then Check Alive will be unselected for all same types of sensors.
Also, the Check Alive is not working for some sensors while working for the same type of sensor.

It feels weird, and not stable.

![image](https://user-images.githubusercontent.com/7469537/147619776-cf9cbaea-6995-4410-bf25-66b6f7895a6a.png)

**Comment by flic** [comment]
If you unselect check alive on a sensor type it should be unselected for all sensors of that type so that sounds about right, if I understood you correctly.

It sounds weird that heartbeat works for some sensors of a specific type but not others of the same type. I'll look into it, any extra information you can give me would be great.

**Comment by alexsahka** [comment]
I just thought that "Check Alive" is designed to use per "thing", but not per "type".

Here is a question: If I have the same kind but multiple sensors. Then how "Check Alive" function works?

For Example, if I have 5 temperature Zigbee sensors and one sensor stops sending updates how do I know if this happening?
I'm reusing "type" (config) because all 5 sensors same kind of sensors.

I think "Check Alive" should work per "thing", but not per "type". 

Sorry if this is confusing.

**Comment by flic** [comment]
The configuration is per type, but the check is per thing. Let's see if I can explain this a bit better.

My thinking here is that all instances of a specific type of device should check heartbeat in the same way and at the same rate.

For instance, let's say I have a type of sensor that should check in at least once an hour. I configure that type of sensor with a heartbeat of 3600 seconds. Every instance of that sensor, every "thing", keeps its own record of the last time it received data, and when that time > 3600 seconds ago that thing gets marked as alive=false and you get a red dot in the GUI on it.

There's one more parameter that plays into this, and that's the heartbeat check interval configured in the event handler. The event handler checks the heartbeat on all things, so if the heartbeat value for a specific thing is set to 60 seconds but the event handler check interval is set to 3600 seconds it might take up to an hour for the alive value to change on that thing. I think I defaulted the event handler value to 3600, which in hindsight might be a bit high. I should probably change that to 60 seconds or so.

**Comment by alexsahka** [comment]
This is great, If every "thing", keeps its own record.

But I saw behavior when I updated 3 different  "things" then clicked to Deploy NodeRed and GUI for 3 different  "things" changed from red to green at the same time. Maybe this has happened initially the first time but it was definitely felt not right.

Again, sorry for the confusion.

**Comment by flic** [comment]
There's a 5 sec time delay after deployment until the event handler runs the first check so I'm guessing that might be the explanation for the behavior you saw, but I'll keep an eye out. Let me know if you see anything else strange.

**Comment by alexsahka** [comment]
Sure, Thanks!
