### ISSUE TITLE
hal2Thing Last  Will Not working

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal2#5]
hal2Thing Last  Will Status Not working, green dot not changing to red. But hal2Event showing changes from boolean: true to boolean: false.

Worked before.

**Comment by flic** [comment]
So you can see Alive changing from true to false, but the GUI still shows a green dot?

**Comment by alexsahka** [comment]
> but the GUI still shows a green dot?

Yes, correct.

**Comment by alexsahka** [comment]
Updated to v1.4.1 version.
GUI still always shows a green dot.

Is this issue with Last Will GUI still existing in the v1.4.1 version?

**Comment by flic** [comment]
I'm not able to reproduce the problem. Can you post an example flow?

**Comment by flic** [comment]
Hang on, found it! Screwed up a bit when I fixed heartbeat earlier.

**Comment by flic** [comment]
Fixed in v1.5.2

**Comment by alexsahka** [comment]
> Screwed up a bit when I fixed heartbeat earlier.

Yes, the Last Will worked before that. Thanks!
