### ISSUE TITLE
Value/ Gate/Event breaks when any thing node is not properly setup

### ISSUE THREAD

**Issue by RSWilli** [flic/node-red-contrib-hal2#6]
```
Uncaught (in promise) TypeError: thingType is undefined
    oneditprepare ....
    ....
```

I think it happens in this line: https://github.com/flic/node-red-contrib-hal2/blob/main/core/value.html#L31 when the Thing node is not properly set up

in that case the oneditprepare crashes and doesn't show any thing nodes available, not even an error

when that happens the gate and event are also not functional

the error handling in these nodes should make use of try/catch more

----

I reached this state because the nodes from the examples were not properly deleted when I deleted the flows. that was fixed by a page reload.

**Comment by flic** [comment]
That's an excellent point, I'll look into it. I'm fairly new at Javascript and it kinda shows... ;)
