### ISSUE TITLE
actions do not work with topic filter != ""

### ISSUE THREAD

**Issue by RSWilli** [flic/node-red-contrib-hal2#8]
actions don't do anything, when a topicfilter has been set

although you can choose the item to update, it wont actually update the item

without the topicfilter, the target thing will update all items to the value given to action, which is undesired in my opinion

**Comment by flic** [comment]
Not sure I understand what you mean. Can you show me an example of what you're trying to do?

**Comment by RSWilli** [comment]
![image](https://user-images.githubusercontent.com/18500203/148557905-8672707c-92b0-4254-9770-e838de9eb32a.png)

I have a thermostat thing type and 5 thermostat things, each with a different id as attribute

I have set the topic filter for each of the items: battery, temp and target

I now want to set each of the items somehow and I figured I'd do it via the action node, where I can select an item and set a value either from payload or directly

![image](https://user-images.githubusercontent.com/18500203/148558500-618374b6-af25-4d04-927f-ec29866c56f2.png)


but the action doesn't actually update the item, when a topicfilter is set

when I remove the topicfilter, all items get updated, not just the temp item

**Comment by flic** [comment]
Oh, okay, I see.

My thinking here is that a Thing represents a physical device. The input should be coming from the device, and the output should be sent out to the device. A command is supposed to be sent from the Thing to the device, hopefully result in a status change, which the device would then send out to be received by the Thing input, and thus update the Item value.

I realized fairly recently that there are scenarios where you'd want to create a virtual thing, for example a thing representing a scene, and so I added the option to loopback the command. It's pretty much a virtual wire connecting the Thing output to the Thing input, nothing more. As such, the command payload and topic must be formatted in a way that the input understands and accepts.

Try this:

![Skärmavbild 2022-01-07 kl  15 58 23](https://user-images.githubusercontent.com/400673/148563582-d9c2d77c-d616-47ec-8294-a38f5ae80919.png)

I'm considering making it possible to update an item value directly, which I think is what you'd like to do, but it would break the concept of the Thing being a virtual representation of a physical device so I'm not sure. Still thinking about it.

**Comment by flic** [comment]
I made some changes in v1.8.0 that might be closer to what you want.

The value node can both get and set item values now. The item state is set directly without passing through any topic filters or ingress functions.

![Skärmavbild 2022-01-08 kl  18 15 40](https://user-images.githubusercontent.com/400673/148653444-e4f66367-4727-4d2d-bbfd-0333d4d3b6c3.png)
