### ISSUE TITLE
Event nodes throw error if added from the palette

### ISSUE THREAD

**Issue by minedaddy** [flic/node-red-contrib-hal2#9]
Hi frtnbach,

I've been converting my flows with HAL2 since I discovered it a few days ago and my setup works beautifully. Nice job! Along the way I've installed the newest updates for HAL2 as you've made them available. Today, I added a new HAL2 event node to my flow and got "TypeError: convertTo[node.compareType] is not a function".

I did a lot of tests and discovered that if I copy and paste an existing event node then change the settings it works as expected. If, however, I drag a new event node from the palette I get the error no matter what.

Poking around the exported flow JSON I see that the node I pasted has the JSON element "compareType": "num" while this element is missing from the node from the palette. So it looks like convertTo fails at runtime because the type parameter is missing.

BTW: Using HAL2 has greatly simplified and streamlined my setup.
Thanks!

**Comment by flic** [comment]
Sorry 'bout that, fixed in v1.9.2.

Thanks for the detailed report!
